module.exports = {
    theme: {
        extend: {
            fontFamily: {
                'lato': [
                    'lato',
                    'system-ui',
                    'BlinkMacSystemFont',
                    '-apple-system',
                    'Segoe UI',
                    'Roboto',
                    'Oxygen',
                    'Ubuntu',
                    'Cantarell',
                    'Fira Sans',
                    'Droid Sans',
                    'Helvetica Neue',
                    'sans-serif',
                ],
            },
        },
        fill: theme => ({
            current: 'currentColor',
            'green-100': theme('colors.green.100'),
            'green-200': theme('colors.green.200'),
            'green-300': theme('colors.green.300'),
            'green-400': theme('colors.green.400'),
            'green-500': theme('colors.green.500'),
            'green-600': theme('colors.green.600'),
            'green-700': theme('colors.green.700'),
            'green-800': theme('colors.green.800'),
            'green-900': theme('colors.green.900'),
            'yellow-100': theme('colors.yellow.100'),
            'yellow-200': theme('colors.yellow.200'),
            'yellow-300': theme('colors.yellow.300'),
            'yellow-400': theme('colors.yellow.400'),
            'yellow-500': theme('colors.yellow.500'),
            'yellow-600': theme('colors.yellow.600'),
            'yellow-700': theme('colors.yellow.700'),
            'yellow-800': theme('colors.yellow.800'),
            'yellow-900': theme('colors.yellow.900'),
            'red-100': theme('colors.red.100'),
            'red-200': theme('colors.red.200'),
            'red-300': theme('colors.red.300'),
            'red-400': theme('colors.red.400'),
            'red-500': theme('colors.red.500'),
            'red-600': theme('colors.red.600'),
            'red-700': theme('colors.red.700'),
            'red-800': theme('colors.red.800'),
            'red-900': theme('colors.red.900'),
        }),
        width: theme => ({
            auto: 'auto',
            ...theme('spacing'),
            '1/2': '50%',
            '1/3': '33.33333%',
            '2/3': '66.66667%',
            '1/4': '25%',
            '3/4': '75%',
            '1/5': '20%',
            '2/5': '40%',
            '3/5': '60%',
            '4/5': '80%',
            '1/6': '16.66667%',
            '5/6': '83.33333%',
            '1/7': '14.286%',
            '2/7': '28.572%',
            '3/7': '42.858%',
            '4/7': '57.144%',
            '5/7': '71.43%',
            '6/7': '85.716%',
            full: '100%',
            screen: '100vw',
        }),
        minHeight: {
            '0': '0',
            full: '100%',
            screen: '100vh',
        }
    },
    variants: {
        textColor: ['responsive', 'hover', 'focus', 'group-hover'],
        fill: ['hover', 'focus', 'group-hover'],
    },
    plugins: [
    // Some useful comment
    ]
}
